services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tg
      POSTGRES_PASSWORD: tgpass
      POSTGRES_DB: tgmon
    ports: ["5432:5432"]
    volumes:
      - ./postgres:/var/lib/postgresql/data

  watcher:
    build: ./watcher
    depends_on: [redis]
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
      SESSION_DIR: /data/session
      CONFIG_PATH: /config/config.yml
      STREAM_KEY: tg:messages
    volumes:
      - watcher_session:/data/session
      - ./watcher/config.test.yml:/config/config.yml:ro
    restart: unless-stopped

  ollama:
    profiles: ["llm"]
    image: ollama/ollama:latest
    container_name: tg-ollama
    ports: ["11434:11434"]
    volumes:
      - ./ollama:/root/.ollama
      # - ./ollama-import:/import:ro
    gpus: all
    restart: unless-stopped

  worker:
    profiles: ["llm"]
    build: ./worker
    depends_on: [redis, postgres, ollama]
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
      PG_DSN: postgresql://tg:tgpass@postgres:5432/tgmon
      STREAM_KEY: tg:messages
      STREAM_GROUP: tg-classifiers
      STREAM_CONSUMER: worker-1

      # Ollama на хосте
      #OLLAMA_URL: http://host.docker.internal:11434
      # Worker ходит в ollama по имени сервиса в compose-сети
      OLLAMA_URL: http://ollama:11434
      # модель можно менять
      OLLAMA_MODEL: llama3.2

      BATCH_SIZE: "8"
      BLOCK_MS: "5000"
      CLAIM_IDLE_MS: "60000"

      PROMPT_PATH: /config/prompt.txt
    volumes:
      - ./worker/prompt.txt:/config/prompt.txt:ro
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  redis_data:
  watcher_session:
