services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    image: postgres:16-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: tg
      POSTGRES_PASSWORD: tgpass
      POSTGRES_DB: tgmon
    volumes:
      - ./postgres:/var/lib/postgresql/data

  watcher:
    build: ./watcher
    depends_on: [redis]
    env_file: .env
    command:
      - --config
      - /etc/tg-monitor/config.yml
      - --verbose
    volumes:
      - watcher_session:/data/session
      - ./watcher.config.yml:/etc/tg-monitor/config.yml:ro
    restart: unless-stopped

  ollama:
    profiles: ["llm"]
    image: ollama/ollama:latest
    container_name: tg-ollama
    ports: ["11434:11434"]
    volumes:
      - ./ollama:/root/.ollama
    gpus: all                       # launch LLM on GPU
    restart: unless-stopped

  # This service uses local ollama model
  worker-local:
    profiles: ["llm"]
    build: ./worker
    depends_on: [redis, postgres, ollama]
    env_file: .env
    environment:
      PG_DSN: postgresql://tg:tgpass@postgres:5432/tgmon
      OLLAMA_HOST: http://ollama:11434
      LLM_MODEL: llama3.2
    command:
      - --llm-local
      - --verbose
    volumes:
      - ./worker/prompt.txt:/etc/tg-monitor/prompt.txt:ro
    restart: unless-stopped

  # This service uses cloud LLM API (OpenAI-compatible)
  worker-cloud:
    profiles: ["cloud"]
    build: ./worker
    depends_on: [redis, postgres]
    env_file: .env
    environment:
      PG_DSN: postgresql://tg:tgpass@postgres:5432/tgmon
      LLM_MODEL: qwen.qwen3-coder-30b-a3b-instruct
    command:
      - --llm-cloud
      - --verbose
    volumes:
      - ./worker/prompt.txt:/etc/tg-monitor/prompt.txt:ro
    restart: unless-stopped

  # This service does NOT uses ay LLM
  worker-trivial:
    profiles: ["trivial"]
    build: ./worker
    depends_on: [redis, postgres]
    env_file: .env
    environment:
      PG_DSN: postgresql://tg:tgpass@postgres:5432/tgmon
    command:
      - --verbose
    volumes:
      - ./worker/prompt.txt:/etc/tg-monitor/prompt.txt:ro
    restart: unless-stopped

volumes:
  redis_data:
  watcher_session:
