at_config_path = 'config_path'
at_enabled = 'enabled'
at_exclude_any = 'exclude_any'
at_filters = 'filters'
at_include_any = 'include_any'
at_matched_only = 'matched_only'
at_min_length = 'min_length'
at_name = 'name'
at_redis_url = 'redis_url'
at_routing = 'routing'
at_session_dir = 'session_dir'
at_stream_key = 'stream_key'

at_REDIS_URL = 'REDIS_URL'
at_TELEGRAM_API_HASH = 'TELEGRAM_API_HASH'
at_TELEGRAM_API_ID = 'TELEGRAM_API_ID'
at_telegram_api_hash = 'telegram_api_hash'
at_telegram_api_id = 'telegram_api_id'
